# Generated by Django 3.1.2 on 2021-01-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, max_length=30, verbose_name='info'),
        ),
    ]
