# Generated by Django 3.1.2 on 2020-12-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201212_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
