# Generated by Django 3.1.2 on 2021-01-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210102_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='editing',
        ),
    ]
