# Generated by Django 3.0.8 on 2020-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_auto_20200906_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Главная', max_length=100, unique=True),
        ),
    ]
