# Generated by Django 3.1.1 on 2020-09-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0005_auto_20200913_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
