# Generated by Django 3.1.1 on 2020-09-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0006_auto_20200913_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
    ]
