# Generated by Django 3.1.1 on 2020-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0007_auto_20200920_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
