# Generated by Django 3.1.1 on 2020-10-08 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0008_todo_editing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 8, 13, 49, 41, 697584), verbose_name='Дата регистрации'),
        ),
    ]
