<template>
  <div class="row">
    <div class="col-6 offset-3 text-center mt-5">
      <div class="loadingio-spinner-spin-yg37vrw889t">
        <div class="ldio-1aollihn9b2">
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
          <div><div></div></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'preloader'
  }
</script>

<style>
  @keyframes ldio-1aollihn9b2 {
    0% {
      opacity: 1;
      backface-visibility: hidden;
      transform: translateZ(0) scale(1.34, 1.34);
    }
    100% {
      opacity: 0;
      backface-visibility: hidden;
      transform: translateZ(0) scale(1, 1);
    }
  }
  .ldio-1aollihn9b2 div > div {
    position: absolute;
    width: 11.100000000000001px;
    height: 11.100000000000001px;
    border-radius: 50%;
    background: #c4c4c4;
    animation: ldio-1aollihn9b2 0.9345794392523364s linear infinite;
  }
  .ldio-1aollihn9b2 div:nth-child(1) > div {
    left: 78.5px;
    top: 49.50000000000001px;
    animation-delay: -0.8307372793354101s;
  }
  .ldio-1aollihn9b2 > div:nth-child(1) {
    transform: rotate(0deg);
    transform-origin: 84.05000000000001px 55.050000000000004px;
  }
  .ldio-1aollihn9b2 div:nth-child(2) > div {
    left: 72.5px;
    top: 68.5px;
    animation-delay: -0.7268951194184838s;
  }
  .ldio-1aollihn9b2 > div:nth-child(2) {
    transform: rotate(40deg);
    transform-origin: 78.05000000000001px 74.05000000000001px;
  }
  .ldio-1aollihn9b2 div:nth-child(3) > div {
    left: 54.50000000000001px;
    top: 78.5px;
    animation-delay: -0.6230529595015576s;
  }
  .ldio-1aollihn9b2 > div:nth-child(3) {
    transform: rotate(80deg);
    transform-origin: 60.050000000000004px 84.05000000000001px;
  }
  .ldio-1aollihn9b2 div:nth-child(4) > div {
    left: 35.50000000000001px;
    top: 74.5px;
    animation-delay: -0.5192107995846313s;
  }
  .ldio-1aollihn9b2 > div:nth-child(4) {
    transform: rotate(120deg);
    transform-origin: 41.050000000000004px 80.05000000000001px;
  }
  .ldio-1aollihn9b2 div:nth-child(5) > div {
    left: 22.500000000000007px;
    top: 59.50000000000001px;
    animation-delay: -0.41536863966770504s;
  }
  .ldio-1aollihn9b2 > div:nth-child(5) {
    transform: rotate(160deg);
    transform-origin: 28.050000000000004px 65.05000000000001px;
  }
  .ldio-1aollihn9b2 div:nth-child(6) > div {
    left: 22.500000000000007px;
    top: 40.50000000000001px;
    animation-delay: -0.3115264797507788s;
  }
  .ldio-1aollihn9b2 > div:nth-child(6) {
    transform: rotate(200deg);
    transform-origin: 28.050000000000004px 46.050000000000004px;
  }
  .ldio-1aollihn9b2 div:nth-child(7) > div {
    left: 35.50000000000001px;
    top: 24.500000000000007px;
    animation-delay: -0.20768431983385252s;
  }
  .ldio-1aollihn9b2 > div:nth-child(7) {
    transform: rotate(240deg);
    transform-origin: 41.050000000000004px 30.050000000000004px;
  }
  .ldio-1aollihn9b2 div:nth-child(8) > div {
    left: 54.50000000000001px;
    top: 21.500000000000007px;
    animation-delay: -0.10384215991692626s;
  }
  .ldio-1aollihn9b2 > div:nth-child(8) {
    transform: rotate(280deg);
    transform-origin: 60.050000000000004px 27.050000000000004px;
  }
  .ldio-1aollihn9b2 div:nth-child(9) > div {
    left: 72.5px;
    top: 31.500000000000007px;
    animation-delay: 0s;
  }
  .ldio-1aollihn9b2 > div:nth-child(9) {
    transform: rotate(320deg);
    transform-origin: 78.05000000000001px 37.050000000000004px;
  }
  .loadingio-spinner-spin-yg37vrw889t {
    width: 111px;
    height: 111px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-1aollihn9b2 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-1aollihn9b2 div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
</style>
